### What is numpy?  (Numerical Python)

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

- initally data Science pe kaam MATLAB jaise tools ya R programming language me kya jata tha (approx 2008-09) uss time pe python ko prefer nahi kya jata tha data Science ke lye qki ye bahut slow language tha tabhi Numpy Library banaya (basically numpy likha gya hai c me) jisme ki array ka concept aaya jisse ki ye language bhi bahut fast ho gya 

# creating Numpy Array

In [1]:
# Importing the Numpy
import numpy as np  # np(alies name) ek short name dye hain bass taki aage baar baar Numpy nahi likhna pade np se kaam chal jaye

In [19]:
#1D array   -> simply karna kuch nahi hai bass 1D list provide kara dena hai
a=np.array([1,2,3])
print(a)
print(type(a))  # 1D also called as  vector

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
a=np.array(['jay','ram'])
a

array(['jay', 'ramjsdb'], dtype='<U7')

In [9]:
a=np.array(['jay','ram',2])
a

array(['jay', 'ram', '2'], dtype='<U11')

In [23]:
#2D & 3D array   -> simply karna kuch nahi hai bass 2D & 3D list provide kara dena hai
b=np.array([[1,2,3],[3,4,5]])
print(b)
print(type(b))   # 2D also called as  matrix

[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>


In [7]:
# 3D
a=np.array([[[1,2,3],[5,4,3]],[[4,5,6],[5,4,3]],[[7,8,9],[5,4,3]]])
a

array([[[1, 2, 3],
        [5, 4, 3]],

       [[4, 5, 6],
        [5, 4, 3]],

       [[7, 8, 9],
        [5, 4, 3]]])

In [6]:
# ndmin     =>aap apne according dimension define karte ho
arr=np.array([1,2,3,4],ndmin=10)  
arr

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [31]:
# dtype => apne man se array ka type bana sakte hain by default int hota hai isse float , bool , complex etc bana sakte hain
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [11]:
np.array([1,2,3,0],dtype=bool)

array([ True,  True,  True, False])

In [35]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [37]:
# np.arange => similar as range function
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [41]:
# with reshape  => basically reshape karne me kaam aata hai
np.arange(1,11).reshape(2,5)  # ye sare element ko jo 1D me hona tha usko reshape karke 2D me with 2-rows and 5-columns me convert kar
         # dega ye tabhi hoga jabki possible hai ye nahi ki hum bale 5 x 5 kar do jabki itne element hi nahi hain humare pass

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
# np.ones and np.zeros => aap isko use karke ek numpy array bana sakte ho jiske sare ke sare element either zero ho ya one bass aapko tuples me 2D array 
#ka size dena hai
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# yadi kisi random number se initialize karana ho to
#np.random
np.random.random((3,4))

array([[0.65367038, 0.61962895, 0.36920657, 0.82015751],
       [0.56679943, 0.17207025, 0.70460235, 0.80658213],
       [0.95347863, 0.40823868, 0.16345232, 0.82663729]])

In [9]:
#np.linspace =>linear space isme aap 3 chize provide karate ho (i) lower range ,ii) heigher range iii) the total number that you want
np.linspace(-10,10,8)  #-10 se 10 ke bich me 10 number equal distance pe de dega(initial and final both are included) matlab 2 ka
                         # difference humesa same hoga

array([-10.        ,  -7.14285714,  -4.28571429,  -1.42857143,
         1.42857143,   4.28571429,   7.14285714,  10.        ])

In [25]:
# by default sara  number float me hota hai but agar aapko int me chahaiye to bass {dtype=int} likh do
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [17]:
np.linspace(10,20,6,dtype=int)

array([10, 12, 14, 16, 18, 20])

In [20]:
# np.identity => to print identity matrix
np.identity(3)  # bass size paass kar do

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes
- har numpy array numpy class ka object hai toh har numpy array jo aap bana rahe ho wo numpy class ki kuch arrtibutes ko access kar sakta hai

In [18]:
a1=np.arange(10,dtype=np.int32) # dtype compulsury nahi hai but agar aap 32 bit bale ke sath ya 64 bit ke sath kaam kaena chahate hain ypou choice
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8,dtype=np.int64).reshape(2,2,2)  # simply (2,2,2) batata hai ki 2x2 size ka andar me 2 (pahla number) 2D array hai

In [36]:
a1 #1D array  or vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a2 #2D array

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [40]:
a3  #3D array or tensor

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
# ndim (Number of Dimension)  => simply ki aapka jo array hai wo kitne dimension ka hai
a1.ndim

1

In [4]:
import numpy as np

In [6]:
np.array([1,2,3]).ndim

1

In [44]:
a2.ndim

2

In [46]:
a3.ndim

3

In [48]:
# shape (ye batayega ki har dimension me kitne item hain)
a1.shape

(10,)

In [50]:
a2.shape

(3, 4)

In [52]:
a3.shape

(2, 2, 2)

In [54]:
# size => number of items kitne hain
a1.size

10

In [56]:
a2.size

12

In [58]:
a3.size

8

In [68]:
# itemsize => basically batata hai ki memory me har item kitna size occupy karta hai
a1.itemsize

4

In [70]:
a2.itemsize

8

In [72]:
a3.itemsize

8

In [22]:
np.array([[1,2,3],[4,5,6]]).astype(float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [74]:
# dtype =>ye batata hai ki aapke item ka datatype kya hai
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


## changing Datatype

In [38]:
# astype  => you can change your data type
a4=a3.astype(np.int32)
a4

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
print(a4.dtype)

int32


In [42]:
print(a3.dtype)   # it shows ki changes original bale me nahi hota hai

int64


In [44]:
a5=a3.astype(float)
a5

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [46]:
print(a5.dtype)

float64


## Array Operations

In [49]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [51]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
## scalar Operation

# arithmetic  => kisi particular number se arithmatic operation kara do
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [57]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [59]:
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [61]:
a1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [63]:
a1//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [65]:
a1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [67]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [69]:
# relational  => sabke sab relational operator apply kar sakte ho
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
a2>5  # each element se compare karega ki a2 ka jo each element hai wo 5 se grater hai ki nahi and ek boolean array return karega

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [73]:
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [75]:
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [77]:
# vector operation  => shape same hona chahaiye


# arithmetic

a1



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [81]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [83]:
a1*a2  # corrosponding element product hoga

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [85]:
a1**a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

In [87]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array function

In [3]:
import numpy as np

In [17]:
a1 = np.random.random(5)
#a1 = np.round(a1*100)
a1

array([0.11343832, 0.98235722, 0.05013409, 0.8468819 , 0.98127073])

In [19]:
# random number -> rand,randn,ranf,randint

a=np.random.rand(10)
a

array([0.34605265, 0.1875996 , 0.67101219, 0.97216955, 0.72828204,
       0.87412899, 0.52245757, 0.60122   , 0.51739623, 0.97997266])

In [10]:
a=np.random.rand(2,4)
a

array([[0.40843536, 0.98472908, 0.15423192, 0.05024507],
       [0.84223149, 0.11024095, 0.62546642, 0.62493099]])

In [12]:
a=np.random.ranf(10)
a

array([0.50113025, 0.50028113, 0.92899553, 0.91632737, 0.77442113,
       0.94794648, 0.69412541, 0.39085533, 0.58093387, 0.08175353])

In [14]:
a=np.random.ranf(2,4)
a

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [16]:
a=np.random.ranf((2,4))  # agar multidimension chahaiye to aap simply ek tuple pass kar do
a

array([[0.98842586, 0.85284128, 0.65288041, 0.75446212],
       [0.35332838, 0.54494872, 0.02990169, 0.11542688]])

In [18]:
a=np.random.randn(4)  # random negative
a

array([-0.66633551,  0.39187368, -1.4242592 , -0.23321945])

In [32]:
a=np.random.randint(18,25,10)  # 18-25 ke bich me 10 integer value

a

array([21, 24, 18, 22, 23, 23, 23, 21, 20, 24])

In [12]:
a1

array([[68., 40., 82.],
       [11., 29., 36.],
       [84., 63., 66.]])

In [14]:
# max/min/sum/prod
np.max(a1)

84.0

In [16]:
np.min(a1)

11.0

In [18]:
np.sum(a1)  # jitna bhi element hai array me sabka sum find karke de dega

479.0

In [20]:
np.prod(a1)   # jitna bhi element hai array me sabka product find karke de dega

894622283089920.0

In [22]:
a1

array([[68., 40., 82.],
       [11., 29., 36.],
       [84., 63., 66.]])

In [24]:
# hum each row ke sath bhi kaam kar sakte hain matlab ki agar need hai ki each row ya each column ka max/min element find karo ya each row 
# ya each column ka sum/product

# axis=0 -> col and 1-> row
np.max(a1,axis=0)  # columne wise maximum element fing karke de dega

array([84., 63., 82.])

In [26]:
np.min(a1,axis=0)

array([11., 29., 36.])

In [28]:
np.sum(a1,axis=0)

array([163., 132., 184.])

In [30]:
np.prod(a1,axis=0)

array([ 62832.,  73080., 194832.])

In [32]:
np.max(a1,axis=1)

array([82., 36., 84.])

In [34]:
np.min(a1,axis=1)

array([40., 11., 63.])

In [36]:
np.sum(a1,axis=1)

array([190.,  76., 213.])

In [38]:
np.prod(a1,axis=1)

array([223040.,  11484., 349272.])

In [40]:
# mean/median/std/var

In [42]:
np.mean(a1)  # sare element ka mean find karke de dega

53.22222222222222

In [44]:
# and ofcourse yaha bhi flexibility hai row wise and column wise bhi find kar sakte ho
np.mean(a1,axis=1)

array([63.33333333, 25.33333333, 71.        ])

In [46]:
np.median(a1)

63.0

In [48]:
np.median(a1,axis=1)

array([68., 29., 66.])

In [50]:
np.var(a1)  # variance

565.9506172839506

In [52]:
np.std(a1)  # standard deviation

23.789716628912387

In [54]:
# trigonometric function
np.sin(a1)

array([[-0.89792768,  0.74511316,  0.31322878],
       [-0.99999021, -0.66363388, -0.99177885],
       [ 0.73319032,  0.1673557 , -0.02655115]])

In [8]:
# dot product => matrix product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [56]:
# log and exponent
np.log(a1)  # har element ka log


array([[4.21950771, 3.68887945, 4.40671925],
       [2.39789527, 3.36729583, 3.58351894],
       [4.4308168 , 4.14313473, 4.18965474]])

In [58]:
np.exp(a1)  # har element ka exponent

array([[3.40427605e+29, 2.35385267e+17, 4.09399696e+35],
       [5.98741417e+04, 3.93133430e+12, 4.31123155e+15],
       [3.02507732e+36, 2.29378316e+27, 4.60718663e+28]])

In [60]:
# round /floop/ceil
a=np.random.random((2,3))*100

In [62]:
a

array([[94.92026349,  5.59729856, 66.3819704 ],
       [71.70719749, 44.80901264,  8.01456459]])

In [64]:
np.round(a)

array([[95.,  6., 66.],
       [72., 45.,  8.]])

In [66]:
np.floor(a)

array([[94.,  5., 66.],
       [71., 44.,  8.]])

In [68]:
np.ceil(a)

array([[95.,  6., 67.],
       [72., 45.,  9.]])

# Indexing and Slicing

In [26]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# normal jaise pahle indexing hota tha and numpy also support +ve as well -ve indexes
a1[-1]

9

In [31]:
a1[0]

0

In [28]:
# 2D
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
#just we have to find 6 => sabse pahle row batao and comma ke baad column batao and row column ka indexing 0 se suru hota hai
a2[1,2]

6

In [36]:
a2[-1,-2]

10

In [39]:
# 4
a2[1,0]

4

In [38]:
# 3D
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
# iss 3D array me 2 - 2D array  hai => to pahle ye batao ki kon se 2D array se element find karna hai
# find 5
a3[1,0,1]  # 1st 2D array , 0th row and 1st column

5

In [40]:
a3[-2,0,1]

1

In [45]:
# 0
a3[0,0,0]

0

In [47]:
#6
a3[1,1,0]

6

### Slicing  => ek sath multiple item ko bhi nikal sakte ho

In [50]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# 1D me sab kuch same hai python kee jaisa
# find 2,3,4
a1[2:5]

array([2, 3, 4])

In [54]:
a1[2:5:2]

array([2, 4])

In [56]:
# 2D
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
# find 1st row
a2[0,:]  # kon sa row chahaiye and kon sa column chahaiye to mujhe sare column chahaiye 1st row ka to sirf colon(seperate with column)

array([0, 1, 2, 3])

In [62]:
# find 2nd column
a2[:,2]

array([ 2,  6, 10])

In [64]:
# 5,6,
# 9,10
a2[1:,1:3] #=> 1st row se suru karo and 1st and 2nd column since last is exclusive so 3rd column print nahi hoga

array([[ 5,  6],
       [ 9, 10]])

In [66]:
 #0,3
 #8,11
a2[::2,::3]  # comma ke pahla bala batata hai ki kon sa row chahaiye to mujhe sare row chahaiye with 1 alternate and comma ke baad 
              #bala batata hai ki kon kon sa column chahaiye to sare chahaiye but 2 column alternative

array([[ 0,  3],
       [ 8, 11]])

In [68]:
# 1,3
# 9,11
a2[::2,1::2]  

array([[ 1,  3],
       [ 9, 11]])

In [72]:
# 4,7
a2[1,::3]

array([4, 7])

In [74]:
#1,2,3
#5,6,7
a2[0]

array([0, 1, 2, 3])

In [80]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [82]:
#1,3
#5,7
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [90]:
#3D
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [93]:
# bich bala array find karo
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [95]:
# 1st and last bala chahaiye
a3[0::2] #or,a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
#1st 2D array ka 1st indexed row (3,4,5)
a3[0,1,:]

array([3, 4, 5])

In [101]:
#2nd bala array ka 2nd column(10,13,16)
a3[1,:,1]

array([10, 13, 16])

In [103]:
#22,23
#25,26
a3[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

In [115]:
#0,2
#18,20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [2]:
import numpy as np

In [5]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.transpose(a)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [6]:
np.matrix([[1,2,3],[4,5,6],[7,8,9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
a=np.matrix([1,2,3])
a

matrix([[1, 2, 3]])

# Iterating   
- simply hum Numpy array pe loop chala sakte hain

In [119]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [121]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
for i in a2:
    print(i)  # ek iteration me ek complete row print hota hai so in this code total iteration is 3

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [130]:
for i in a2:
    print(i)
    print()

[0 1 2 3]

[4 5 6 7]

[ 8  9 10 11]



In [138]:
# yadi har element ko seperately print karana hai to
# nditer  => inbult function ka help lena hoga
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [123]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [132]:
for i in a3:
    print(i)  # har iteration me ek 2D array print hota hai

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [134]:
for i in a3:
    print(i)
    print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[18 19 20]
 [21 22 23]
 [24 25 26]]



In [136]:
# yadi har element ko seperately print karana hai to
# nditer  => inbult function ka help lene hoga
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# reshaping

In [142]:
# reshape => Already done

In [144]:
# Transpose => simply jaise matrix me kaam karta hai
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [148]:
# another syntax for transpose
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [150]:
# ravel => kitne bhi dimension ke array ko 1D me convert kar deta hai
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [154]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [156]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [159]:
# ye saare temporary changes ho raha hai

### Stacking
- simply multiple array ko ek dusre ke sath chipka sakte hain
- jab multiple jagah se data aata hai and usse analyse karna ho to Stacking ka use karte hain

In [163]:

a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [165]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [167]:
# horizontal stacking  => shape same hona jaruri hai
np.hstack((a4,a5))  # andar me tuples ke form me array ko pass karte hain

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [171]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [169]:
# vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting
- array ko kaat deta hai and agar  | => kaat raha hai to horizontal spliting and if -- => kaat raha hai to vertical split confuse nahi hona hai
- jab kabhi ek data set se multiple data set create karna ho to iska use karte hain

In [177]:
# horizontal Spliting 
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [181]:
# a4 ko horizontaly 2- parts me split karna hai
np.hsplit(a4,2)  # parameter => 1st - ki kon se array ko split karna hai &&&& 2nd - ki kitna part me katna hai

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [187]:
np.hsplit(a4,3) # error qki 3 equal part me split ho hi nahi sakta hai

ValueError: array split does not result in an equal division

In [189]:
# vertical split
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]